---
# MySQL 5.7
# Docker Based configuration

- name: Create MySQL 5.7 Container
  docker_container:
    name: "{{ service_name }}"
    state: present
    image: "{{ docker_image }}"
    ports:
      - "{{ port }}:3306" # HOST_PORT:CONTAINER_PORT
    volumes:
      - /local/log/mysql/:/var/log/mysql # Logs
      - /local/config/mysql/:/etc/mysql/conf.d # Config
    env:
      "MYSQL_ROOT_PASSWORD": "{{ root_password }}"
      "MYSQL_USER": "{{ user }}"
      "MYSQL_PASSWORD": "{{ user_password }}"
      "MYSQL_DATABASE": "{{ db }}"

- name: Start MySQL 5.7 Container
  docker_container:
    name: "{{ service_name }}"
    state: started

- name: Install MySQL57 Service
  template:
    src=roles/common/templates/systemd_docker.service.j2
    dest=/etc/systemd/system/{{ service_name }}.service
  notify:
    - reload systemd
    - reload service