---
# MySQL Server 5.7

- name: Add MySQL Official Repos
  yum:
    name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present

- name: Install MySQL
  yum: name=mysql-server state=present

- name: Install MySQL Python Management Module
  yum: name=MySQL-python state=present

- name: Start MySQL
  service: name=mysqld state=started enabled=yes

- name: Setup MySQL DB and Credentails
  command: "{{ item }}"
  with_items:
    - mysqladmin -u root password {{ root_password }}
    - mysql -uroot -p{{root_password}} -e"CREATE DATABASE {{db}};"
  args:
    chdir: /root
  ignore_errors: yes

- name: Create .my.cnf file
  template:
    src=client_my.cnf
    dest=/root/.my.cnf

- name: Remove anonymous user account
  mysql_user: name='' host=localhost state=absent

- name: Create the HDMZ Base User and grant permissions
  mysql_user:
    name={{ user }}
    password={{ user_password }}
    priv=*.*:ALL
    state=present

