---
# PhpMyAdmin
# Docker Based configuration

- name: Create/Install PhpMyAdmin Container
  docker_container:
    name: "{{ service_name }}"
    state: present
    image: "{{ docker_image }}"
    ports:
      - "{{ port }}:80" # HOST_PORT:CONTAINER_PORT
    env:
      { "PMA_ARBITRARY" : 1 }

- name: Start PhpMyAdmin Container
  docker_container:
    name: "{{ service_name }}"
    state: started

- name: Install PhpMyAdmin Container
  template:
    src=roles/common/templates/systemd_docker.service.j2
    dest=/etc/systemd/system/{{ service_name }}.service
  notify:
    - reload systemd
    - reload service